name: test

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - name: 📶 Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 📶 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable
      - run: pnpm i
      - run: pnpm run lint
      - run: pnpm run -r typecheck
      - run: pnpm run -r test
      - run: pnpm run -r build
